# Generated by Django 5.2 on 2025-05-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now_add=True),
        ),
    ]
