# Generated by Django 5.2 on 2025-05-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
